/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SCRBurner } from "./SCRBurner";
export type { TestSCR } from "./TestSCR";
export type { TestUSDT } from "./TestUSDT";
